### ISSUE TITLE
Crawler not triggered in manual deploys

### ISSUE THREAD

**Issue by arinthros** [algolia/algoliasearch-netlify#157] opened 2020-12-17 21:18 UTC
The crawler does not seem to be triggering for manual deploys. Any thoughts on how to get it to trigger? I'm not seeing the crawler item in the deploy summary, but the plugin is showing up in the plugins list.

We run a docker process in Gitlab to build a static site, then use the `netlify-cli` npm package to deploy the files.

**gitlab-ci.yml**
```yml
- npm run build
- npm i -g netlify-cli
- netlify deploy --dir build --prod
```

**netlify.toml**
```toml
[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  branches = ['production']
  renderJavaScript = true
```

**Netlify deploy details**
![Screen Shot 2020-12-17 at 3 15 06 PM](https://user-images.githubusercontent.com/6694199/102544809-f8d79d80-407a-11eb-9b54-36452a5d91ff.png)

**Comment by bodinsamuel** [comment] 2020-12-18 09:58
Hi @arinthros 

Thanks for the report, it seems this command `yarn netlify deploy --dir dist --prod` does not trigger the plugins (any of them).
This is probably a limitation from the netlify-cli, maybe you should reach out to https://github.com/netlify/cli to find an alternative that works for you. 

Please let us know what you find,
Best Regards

**Comment by verythorough** [comment] 2020-12-18 17:35
As their name suggests, Build Plugins require a build. Since manual deploys don't run a build, we don't have a build container to run plugins. If you're deploying from CLI, you can run `netlify deploy --build`, which will run a build command (and hence start a build container) before deploying. 

If your site is already "built" at the time you run `netlify deploy --build`, you could modify your build command so that it doesn't re-build your site. I think (but haven't tested) that you could set this in your `netlify.toml` file roughly like so:

```
[context.production]
command = ""
publish = "dist"
```

And then the CLI command would be `netlify deploy --build --prod`. This would skip running any build command (or more accurately, would run an empty build command), but would not skip dependency installation. We're working on adding an option for build to skip dependency installation in the future, though.

**Comment by bodinsamuel** [comment] 2021-01-28 09:25
Closing, working as intended

**Closed by bodinsamuel** 2021-01-28 09:25 UTC

**Comment by tyeeman** [comment] 2023-03-15 03:06
Is this still true - "Build Plugins require a build. Since manual deploys don't run a build, we don't have a build container to run plugins"? I'm just setting up algolia search but using netlify cli (golang version) to upload local files. I don't see any search field on my site. I added the robots.txt file and added the following (my numbers removed) to my index.html file but nothing is showing up.

```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@algolia/algoliasearch-netlify-frontend@1/dist/algoliasearchNetlify.css" />
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@algolia/algoliasearch-netlify-frontend@1/dist/algoliasearchNetlify.js"></script>
<script type="text/javascript">
  algoliasearchNetlify({
    appId: 12345',
    apiKey: '<YOUR_ALGOLIA_SEARCH_API_KEY>',
    siteId: 'id',
    branch: 'master',
    selector: 'div#search',
  });
</script>
```

**Comment by sbellone** [comment] 2023-03-15 09:50
You are mixing up two things:
- _Is this still true - "Build Plugins require a build"_ -> probably, check the logs of your deploy to see if plugins are triggered
- _I don't see any search field on my site_ -> inspect your HTML and check the browser console to understand why the UI doesn't show up (you need a `<div id="search"></div>` somewhere)

**Comment by verythorough** [comment] 2023-03-15 15:18
Build Plugins do still run only during the build, so manual deploys via CLI must include the `--build` flag in order to run the build locally before deploying.

@tyeeman, you mention using the golang version of Netlify CLI. Do you mean this? https://github.com/netlify/netlifyctl
The Go-based `netlifyctl` client was retired some time ago and does not support the `--build` flag.

To run build plugins from the Netlify CLI, you'll need to use the [Node-based client](https://github.com/netlify/cli) that was released in 2018 and is the officially supported Netlify CLI: https://docs.netlify.com/cli/get-started/

**Comment by tyeeman** [comment] 2023-03-16 01:24
OK, thanks. I went to install the node version of CLI and am getting this - 

```
d:\zipfiles-after Jan 18 2023>npm install netlify-cli -g
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#depre
cated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use
 the URLSearchParams API instead.
npm ERR! code 1
npm ERR! path G:\-----New After May 4 2020\TonysAppz\nodejs\node_modules\netlify-cli
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node ./scripts/postinstall.mjs
npm ERR! node:internal/errors:465
npm ERR!     ErrorCaptureStackTrace(err);
npm ERR!     ^
npm ERR!
npm ERR! SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_gethostname returned ENOSYS
(function not implemented)
npm ERR!     at G:\-----New After May 4 2020\TonysAppz\nodejs\node_modules\netlify-cli\node_modules\
@bugsnag\node\dist\bugsnag.js:1082:19
npm ERR!     at G:\-----New After May 4 2020\TonysAppz\nodejs\node_modules\netlify-cli\node_modules\
@bugsnag\node\dist\bugsnag.js:1:88
npm ERR!     at Object.<anonymous> (G:\-----New After May 4 2020\TonysAppz\nodejs\node_modules\netli
fy-cli\node_modules\@bugsnag\node\dist\bugsnag.js:1:323)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1105:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:102:18)
npm ERR!     at Object.<anonymous> (G:\-----New After May 4 2020\TonysAppz\nodejs\node_modules\netli
fy-cli\node_modules\@bugsnag\js\node\notifier.js:1:18) {
npm ERR!   code: 'ERR_SYSTEM_ERROR',
npm ERR!   info: {
npm ERR!     errno: -4054,
npm ERR!     code: 'ENOSYS',
npm ERR!     message: 'function not implemented',
npm ERR!     syscall: 'uv_os_gethostname'
npm ERR!   },
npm ERR!   errno: [Getter/Setter],
npm ERR!   syscall: [Getter/Setter]
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pt\AppData\Local\npm-cache\_logs\2023-03-16T01_07_26_105Z-debug-0.log

d:\zipfiles-after Jan 18 2023>node -v
v16.15.0
```
I'm on Windows7 64bit. Is that the reason I'm getting these errors?

I guess I could copy my files to a github repo and it would likely work fine without installing netlify-cli but I have a newsletter website with 6 years of newsletters. I don't think github would appreciate all those files. Or I could leave all my images, pdf's, etc. on Netlify and put the rest in a repo. But that wouldn't work because the build would overwrite those files already there. If the images, etc. were in another Netlify site and just pointed to by the Github repo files then it should work I would think.

Here is my Deploy Log
```
5:32:16 PM: Starting post processing
5:32:17 PM: Post processing - HTML
5:32:18 PM: Post processing - header rules
5:32:18 PM: Post processing - redirect rules
5:32:18 PM: Post processing done
5:32:19 PM: Section completed: postprocessing
5:32:19 PM: Site is live ✨
```
